apiVersion: v1
kind: Service
metadata:
  name: tls-proxy
  namespace: default
spec:
  clusterIP: 10.43.206.18
  clusterIPs:
  - 10.43.206.18
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: vote-tls
    nodePort: 32233
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: result-tls
    nodePort: 32738
    port: 8083
    protocol: TCP
    targetPort: 8083
  - name: online-shop
    nodePort: 30403
    port: 8084
    protocol: TCP
    targetPort: 8084
  selector:
    app: tls-proxy
  sessionAffinity: None
  type: NodePort
